// src/constants/market.ts
import { teeteePair } from "../types";

export const INITIAL_PAIRS: teeteePair[] = [
    {
        id: 'AZIR',
        name: 'AZIro',
        members: ['AZKi', 'KazamaIroha'],
        price: 100,
        change24h: 0,
        ceoTitle: 'AI董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'FBMO',
        name: 'FubuMio',
        members: ['ShirakamiFubuki', 'OokamiMio'],
        price: 100,
        change24h: 0,
        ceoTitle: 'FM董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'MCMT',
        name: 'miComet',
        members: ['SakuraMiko', 'HoshimachiSuisei'],
        price: 100,
        change24h: 0,
        ceoTitle: 'MM董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'NEFL',
        name: 'NoeFure',
        members: ['ShiraganeNoel', 'ShiranuiFurea'],
        price: 100,
        change24h: 0,
        ceoTitle: 'NF董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'OKKR',
        name: 'OkaKoro',
        members: ['NekomataOkayu', 'InugamiKorone'],
        price: 100,
        change24h: 0,
        ceoTitle: 'OK董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'PKMR',
        name: 'PekoMarin',
        members: ['UsadaPekora', 'HoshoMarin'],
        price: 100,
        change24h: 0,
        ceoTitle: 'PM董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'SSWT',
        name: 'ShishiWata',
        members: ['ShishiroBotan', 'TsunomakiWatame'],
        price: 100,
        change24h: 0,
        ceoTitle: 'SW董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'SRAZ',
        name: 'SorAZ',
        members: ['TokinoSora', 'AZKi'],
        price: 100,
        change24h: 0,
        ceoTitle: 'SA董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    },
    {
        id: 'SBRN',
        name: 'SubaRuna',
        members: ['OozoraSubaru', 'HimemoriRuna'],
        price: 100,
        change24h: 0,
        ceoTitle: 'SR董事長',
        history: [],
        recentTrades: [],
        yesterdayPrice: 100,
        todayVolume: 0,
        status: 'NORMAL' as const,
        warningWeeks: 0,
        pendingInteractions: { liveCollab: 0, largeEvent: 0, newSong: 0 },
        teeteeNews: []
    }
].sort((a, b) => a.name.localeCompare(b.name));
